-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgszYfjLE4Htbhlq6b
7LAWNIJ65tMd3m4vvl+tUYE3NAqgCgYIKoZIzj0DAQehRANCAARXYsInuHQn0lbz
IDADROYf8dPZ/AEMwZgi9Tx8qQtqf+jyyYYn/JsI1/XxNpsQ4TAoaa+IsVbENCuE
puT3VLLz
-----END PRIVATE KEY-----